[theme]
# Primary accent color for interactive elements.
primaryColor = "#FF4B4B"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#1E69FF"

# Color used for almost all text
textColor = '#000000'

[client]
toolbarMode = "minimal"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"